### ISSUE TITLE
Input fields are not work

### ISSUE THREAD

**Issue by ArcadyPerla** [osch/lua-lwtk#1]
I tried running all examples, but on all, I get the same problem. 
When I tried to type any text in input fields, the text appears in the terminal window. The Input field stayed empty. 

I run examples in terminals like this command:
`lua /Users/.../example_lwtk/example01.lua 
`
I use macOS 11.4 Big Sur, and Lua 5.4

**Comment by osch** [comment]
Yes, I also encountered this behaviour on macOS when running the Lua interpreter binary directly from the commandline.

For maxOS GUI program you need a special folder structure with a `Info.plist` file (also known as "bundle").

For example, if you have an application called 'lua.app', then the 'bundle' (or directory hierarchy) might look like this:
```
$ find lua.app -type f
lua.app/Contents/MacOS/lua
lua.app/Contents/Info.plist
```
Here `lua.app/Contents/MacOS/lua` is the Lua interpreter binary and `lua.app/Contents/Info.plist` may look like:

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="0.9">
    <dict>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleExecutable</key>
	<string>lua</string>
	<key>CFBundleIdentifier</key>
	<string>org.lua</string>
	<key>CFBundleName</key>
	<string>lua</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>NSHighResolutionCapable</key>
	<true/>
    </dict>
</plist>
```

With this directory structury you simply may invoke from the commandline:
```
lua.app/Contents/MacOS/lua  /Users/.../example_lwtk/example01.lua 
```

**Comment by ArcadyPerla** [comment]
Thank you for quick and detailed answer!
I created app folder and copied lua and lib binary files

```
arcady@MacBook-Pro-Arkadij ~ % find lua.app -type f
lua.app/Contents/MacOS/luac
lua.app/Contents/MacOS/lua
lua.app/Contents/.DS_Store
lua.app/Contents/lib/pkgconfig/lua.pc
lua.app/Contents/lib/liblua.dylib
lua.app/Contents/lib/liblua.a
lua.app/.DS_Store
lua.app/Info.plist
```

But when I try running my lua.app I get error
```
arcady@MacBook-Pro-Arkadij ~ % /Users/arcady/lua.app 
zsh: permission denied: /Users/arcady/lua.app
```
I tried to change permissions by chmod, but it was useless

**Comment by osch** [comment]
If you are starting the app from the commandline you must invoke the binary directly .i.e. you must invoke
```
$ lua.app/Contents/MacOS/lua  /Users/.../example_lwtk/example01.lua 
```

instead of
```
$ lua.app
```

**Comment by ArcadyPerla** [comment]
Great! It's work now. Thank you!

**Comment by ArcadyPerla** [comment]
Thank you!
