### ISSUE TITLE
Cannot install lwtk on Windows

### ISSUE THREAD

**Issue by Adem-Kurt** [osch/lua-lwtk#10]
I am trying to install lwtk using LuaRocks on Windows, but I am encountering an error. Below is the detailed output:

```
Installing https://luarocks.org/dev/lwtk-scm-0.rockspec  
Missing dependencies for lwtk scm-0:  
   compat53 (not installed)  
   luautf8 (not installed)  
   lpugl_cairo (not installed)  

lwtk scm-0 depends on lua >= 5.1, <= 5.4 (5.4-1 provided by VM: success)  
lwtk scm-0 depends on compat53 (not installed)  
Installing https://luarocks.org/dev/compat53-scm-1.rockspec  

compat53 scm-1 depends on lua >= 5.1, < 5.5 (5.4-1 provided by VM: success)  
x86_64-w64-mingw32-gcc -O2 -c -o liolib.o -IC:\Program Files\lua/include liolib.c  
'x86_64-w64-mingw32-gcc' is not recognized as an internal or external command, operable program or batch file.  

Error: Failed installing dependency: https://luarocks.org/dev/compat53-scm-1.rockspec - Build error: Failed compiling object liolib.o

```

I Installed MinGW64 and Add MinGW64 to the PATH environment variable. but I got same error.

**Comment by osch** [comment]
This looks like a problem with your luarocks installation. It looks like that your luarocks doesn't find the C compiler under the expected name. I'm sorry but I cannot help here further regarding luarocks.

Unfortunetely it's rather difficult to set up a complete luarocks environment that can compile lua C modules under windows. Moreoever for lwtk you need some additional libraries installed  (e.g. cairo) that are not installed by luarocks itself but are considered to be system libraries.

IMHO the easiest way would be do use [msys2](https://www.msys2.org/) for installing all required libraries and to get a working luarocks environment with a C compiler.

**Comment by Adem-Kurt** [comment]
I tried setting up the environment with MSYS2 and it worked! Thanks for your help!
