### ISSUE TITLE
no bitoperations found / module "lpugl" not being found

### ISSUE THREAD

**Issue by Seikm** [osch/lua-lwtk#2]
I was looking for some easy solution to make GUI in pure lua, and I found your project. But honestly I can't quite understand how to use it. I don't know if the problem is me or the program. (probably me)

Should I just create a .lua file and run normally with `lua (file)`? Or do I have to do something else?
I tried to run the `example01.lua` and this error happens:
![image](https://user-images.githubusercontent.com/37481700/186058131-2b86f6ac-8640-4b7d-9711-7ea3e293637d.png)
I looked at this `btest.lua` file, and it seems that the error is not finding the library "lpugl". But I already have it installed, maybe the error is with lpugl?

I'm using Linux (X11) with Lua 5.4.4.

**Comment by osch** [comment]
Yes, it seems that lpugl is not installed.
What happens if you type `require("lpugl")` at the lua command prompt?

**Comment by Seikm** [comment]
Thanks for the quick response. Yes, the library is not being found
![image](https://user-images.githubusercontent.com/37481700/186145949-3ce2446f-99f8-4a92-aa18-d41966bd6f81.png)
Installing again, the library is installed normally. And it still doesn't work
![image](https://user-images.githubusercontent.com/37481700/186147392-7ed21a1e-85ca-4928-b579-a5bec8615416.png)
I believe it is a problem of not finding the library path, do you have any idea what the library path is?

**Comment by osch** [comment]
So it seems that your lua path does not include the location where luarocks installs packages.

you can view the current path for binary modules in the lua interpreter by typing `print(package.cpath)`.

You can invoke `luarocks show lpugl` on the shell commandline to get information about where luarocks installed lpugl. 

Read the lua documentation about  `require`: https://www.lua.org/manual/5.4/manual.html#pdf-require

See also the luarocks explanation: https://github.com/luarocks/luarocks/wiki/Using-LuaRocks#rocks-trees-and-the-lua-libraries-path

**Comment by Seikm** [comment]
Thanks again for the quick and detailed response. That was actually the error, now it's working.

In case anyone has the same error:
The library was installed in `/usr/lib/lua/5.4`, but lua's standard require doesn't have a path there (only for lib64).
To set the paths, just modify your `/home/.bashrc` file and put in the end:
`export LUA_PATH=";;/usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua"`
`export LUA_CPATH=";;/usr/lib/lua/5.4/?.so;/usr/lib/lua/5.4/?/init.lua"`
(This will set the paths permanently)
