### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by lastlos** [osch/lua-lwtk#5]
Hi. I'm  new in Lua and I want to create a GUI app. I made a research about this and then I saw this toolkit. But I don't know how to download it. Can anybody help me to this? (I tried with luarocks but dependences doesn't installs)

**Comment by Frityet** [comment]
> Hi. I'm  new in Lua and I want to create a GUI app. I made a research about this and then I saw this toolkit. But I don't know how to download it. Can anybody help me to this? (I tried with luarocks but dependences doesn't installs)

What's the error with luarocks

**Comment by lastlos** [comment]
> > Hi. I'm  new in Lua and I want to create a GUI app. I made a research about this and then I saw this toolkit. But I don't know how to download it. Can anybody help me to this? (I tried with luarocks but dependences doesn't installs)
> 
> What's the error with luarocks

lpupgl and cairo never installs.

**Comment by osch** [comment]
> lpugl and cairo never installs. (Because some files can't find)

Which platform are you using? Windows, Linux or MacOS?

Luarocks cannot install libraries that are considered system libraries, like cairo. They must be installed by other tools. E.g. using `apt-get` for Ubuntu/Debian or `brew` for MacOS.

**Comment by lastlos** [comment]
> > lpugl and cairo never installs. (Because some files can't find)
> 
> Which platform are you using? Windows, Linux or MacOS?
> 
> Luarocks cannot install libraries that are considered system libraries, like cairo. They must be installed by other tools. E.g. using `apt-get` for Ubuntu/Debian or `brew` for MacOS.

I'm in a Ubuntu variant linux distro. I didn't know cairo is a lib should install using system repos. Sorry 'bout that and sorry 'bout writing too late.
