### ISSUE TITLE
Is LWTK has grid or treeview?

### ISSUE THREAD

**Issue by lastlos** [osch/lua-lwtk#6]
I decide to make a database program has GUI with Lua. And I think I can use LWTK and Sqlite for this but I need a Treeview to show table. I looked to documentation but I didn't find, is LWTK has grid or treeview?

**Comment by osch** [comment]
Up to now, lwtk doesn't have grid or treeview or something similar.

See also the [README](https://github.com/osch/lua-lwtk#lwtk---lua-widget-toolkit):

_This project is work in progress. First aim is to provide a basic infrastructure for creating and customizing widgets. Second aim is to implement a reasonable set of standard widgets. So far only very simple standard widgets are provided, e.g. lwtk.TextInput and lwtk.PushButton._

**Comment by lastlos** [comment]
> Up to now, lwtk doesn't have grid or treeview or something similar.
> 
> See also the [README](https://github.com/osch/lua-lwtk#lwtk---lua-widget-toolkit):
> 
> _This project is work in progress. First aim is to provide a basic infrastructure for creating and customizing widgets. Second aim is to implement a reasonable set of standard widgets. So far only very simple standard widgets are provided, e.g. lwtk.TextInput and lwtk.PushButton._

Thanks for information. I could not use other interface libraries as easily as lwtk. So I work with lwtk in this times. I believe this project will be very successful and I hope this will grow up. I wish I help but I'm not that good of a Lua programmer.
